// West Loop Chicago Construction Projects Data
// Data compiled from public records and development announcements

const constructionProjects = [
    {
        id: 1,
        name: "1000 W Fulton Market Tower",
        address: "1000 W Fulton Market, Chicago, IL 60607",
        lat: 41.8867,
        lng: -87.6523,
        status: "under-construction",
        type: "mixed-use",
        developer: "Sterling Bay",
        architect: "Bjarke Ingels Group (BIG)",
        floors: 35,
        units: 280,
        retailSqFt: 25000,
        officeSqFt: 0,
        estimatedCost: "$250 million",
        startDate: "2024-03",
        expectedCompletion: "2026-06",
        description: "A striking 35-story mixed-use tower featuring 280 luxury residential units with ground-floor retail space. The building showcases a unique twisted design that maximizes views of the Chicago skyline.",
        features: ["Rooftop terrace", "Fitness center", "Co-working space", "Pet spa", "24/7 concierge"],
        neighborhood: "Fulton Market"
    },
    {
        id: 2,
        name: "Halsted Pointe",
        address: "1400 W Randolph St, Chicago, IL 60607",
        lat: 41.8843,
        lng: -87.6622,
        status: "under-construction",
        type: "residential",
        developer: "Related Midwest",
        architect: "Solomon Cordwell Buenz",
        floors: 28,
        units: 350,
        retailSqFt: 15000,
        officeSqFt: 0,
        estimatedCost: "$180 million",
        startDate: "2024-06",
        expectedCompletion: "2026-09",
        description: "A 28-story residential tower bringing 350 new apartments to the heart of the West Loop. The building features modern amenities and sustainable design elements.",
        features: ["Pool deck", "Yoga studio", "Package room", "Bike storage", "EV charging"],
        neighborhood: "Randolph Street"
    },
    {
        id: 3,
        name: "Morgan Street Mixed-Use",
        address: "939 W Morgan St, Chicago, IL 60607",
        lat: 41.8855,
        lng: -87.6507,
        status: "proposed",
        type: "mixed-use",
        developer: "Shapack Partners",
        architect: "Hartshorne Plunkard Architecture",
        floors: 22,
        units: 195,
        retailSqFt: 20000,
        officeSqFt: 45000,
        estimatedCost: "$145 million",
        startDate: null,
        expectedCompletion: "2028-01",
        description: "A proposed 22-story mixed-use development that would add residential units, office space, and retail to the growing Morgan Street corridor.",
        features: ["Green roof", "Public plaza", "Underground parking", "Smart home technology"],
        neighborhood: "Near West Side"
    },
    {
        id: 4,
        name: "The Ogden",
        address: "1640 W Ogden Ave, Chicago, IL 60612",
        lat: 41.8651,
        lng: -87.6693,
        status: "completed",
        type: "residential",
        developer: "Marquette Companies",
        architect: "Pappageorge Haymes Partners",
        floors: 18,
        units: 220,
        retailSqFt: 8000,
        officeSqFt: 0,
        estimatedCost: "$95 million",
        startDate: "2022-08",
        expectedCompletion: "2024-11",
        description: "An 18-story residential building that recently completed construction, offering 220 modern apartments in a transit-oriented location near the CTA Blue Line.",
        features: ["Clubroom", "Outdoor grills", "Dog run", "Business center", "Storage units"],
        neighborhood: "Illinois Medical District"
    },
    {
        id: 5,
        name: "Fulton Labs II",
        address: "915 W Fulton Market, Chicago, IL 60607",
        lat: 41.8866,
        lng: -87.6501,
        status: "under-construction",
        type: "commercial",
        developer: "Trammell Crow Company",
        architect: "Perkins&Will",
        floors: 16,
        units: 0,
        retailSqFt: 12000,
        officeSqFt: 425000,
        estimatedCost: "$310 million",
        startDate: "2024-01",
        expectedCompletion: "2026-03",
        description: "A state-of-the-art life sciences building expanding Fulton Market's growing biotech hub. Features purpose-built lab space with advanced ventilation and infrastructure.",
        features: ["Lab-ready floors", "Conference center", "Cafeteria", "Loading docks", "Backup generators"],
        neighborhood: "Fulton Market"
    },
    {
        id: 6,
        name: "Peoria Green Residences",
        address: "845 W Peoria St, Chicago, IL 60607",
        lat: 41.8879,
        lng: -87.6482,
        status: "approved",
        type: "residential",
        developer: "Focus Development",
        architect: "GREC Architects",
        floors: 12,
        units: 120,
        retailSqFt: 5000,
        officeSqFt: 0,
        estimatedCost: "$65 million",
        startDate: "2026-03",
        expectedCompletion: "2028-06",
        description: "A 12-story sustainable residential building designed to achieve LEED Platinum certification. Features extensive green spaces and energy-efficient systems.",
        features: ["Solar panels", "Rainwater collection", "Community garden", "EV charging", "Geothermal heating"],
        neighborhood: "Fulton Market"
    },
    {
        id: 7,
        name: "Sangamon Square",
        address: "300 N Sangamon St, Chicago, IL 60607",
        lat: 41.8873,
        lng: -87.6514,
        status: "under-construction",
        type: "mixed-use",
        developer: "CA Ventures",
        architect: "Antunovich Associates",
        floors: 24,
        units: 310,
        retailSqFt: 18000,
        officeSqFt: 35000,
        estimatedCost: "$175 million",
        startDate: "2024-09",
        expectedCompletion: "2026-12",
        description: "A 24-story mixed-use development featuring luxury apartments, boutique office space, and curated retail experiences at street level.",
        features: ["Sky lounge", "Theater room", "Golf simulator", "Spa", "Valet parking"],
        neighborhood: "Fulton Market"
    },
    {
        id: 8,
        name: "Lake Street Lofts",
        address: "1112 W Lake St, Chicago, IL 60607",
        lat: 41.8854,
        lng: -87.6557,
        status: "completed",
        type: "residential",
        developer: "Fifield Companies",
        architect: "FitzGerald Associates",
        floors: 8,
        units: 85,
        retailSqFt: 6500,
        officeSqFt: 0,
        estimatedCost: "$42 million",
        startDate: "2023-02",
        expectedCompletion: "2024-08",
        description: "An 8-story boutique residential building featuring loft-style apartments with industrial design elements that pay homage to the neighborhood's meatpacking history.",
        features: ["Exposed brick", "High ceilings", "Rooftop deck", "Fitness center"],
        neighborhood: "West Loop Gate"
    },
    {
        id: 9,
        name: "Madison & Racine Tower",
        address: "1201 W Madison St, Chicago, IL 60607",
        lat: 41.8818,
        lng: -87.6578,
        status: "proposed",
        type: "hotel",
        developer: "Murphy Development Group",
        architect: "Goettsch Partners",
        floors: 30,
        units: 0,
        hotelRooms: 275,
        retailSqFt: 10000,
        officeSqFt: 0,
        estimatedCost: "$200 million",
        startDate: null,
        expectedCompletion: "2029-01",
        description: "A proposed 30-story luxury hotel tower that would bring a major hospitality brand to the West Loop, featuring world-class dining and event spaces.",
        features: ["Rooftop bar", "Ballroom", "Spa & wellness center", "Fine dining", "Valet parking"],
        neighborhood: "Near West Side"
    },
    {
        id: 10,
        name: "Carpenter Court",
        address: "600 N Carpenter St, Chicago, IL 60642",
        lat: 41.8920,
        lng: -87.6538,
        status: "under-construction",
        type: "residential",
        developer: "JDL Development",
        architect: "bKL Architecture",
        floors: 20,
        units: 245,
        retailSqFt: 12000,
        officeSqFt: 0,
        estimatedCost: "$135 million",
        startDate: "2024-04",
        expectedCompletion: "2026-07",
        description: "A 20-story residential tower with 245 apartments ranging from studios to three-bedrooms, designed for modern urban living with expansive amenity spaces.",
        features: ["Infinity pool", "Fire pits", "Coworking lounge", "Private dining room", "Pet grooming"],
        neighborhood: "River West"
    },
    {
        id: 11,
        name: "Green Street Office Hub",
        address: "811 W Green St, Chicago, IL 60607",
        lat: 41.8839,
        lng: -87.6488,
        status: "approved",
        type: "commercial",
        developer: "Sterling Bay",
        architect: "Gensler",
        floors: 14,
        units: 0,
        retailSqFt: 15000,
        officeSqFt: 280000,
        estimatedCost: "$220 million",
        startDate: "2026-06",
        expectedCompletion: "2028-09",
        description: "A 14-story Class A office building designed to attract major corporate tenants with flexible floor plates and best-in-class amenities.",
        features: ["Tenant lounge", "Conference center", "Fitness center", "Bike storage", "Rooftop terrace"],
        neighborhood: "Fulton Market"
    },
    {
        id: 12,
        name: "Union Park Residences",
        address: "1500 W Warren Blvd, Chicago, IL 60607",
        lat: 41.8822,
        lng: -87.6660,
        status: "proposed",
        type: "residential",
        developer: "The Habitat Company",
        architect: "Landon Bone Baker Architects",
        floors: 15,
        units: 180,
        retailSqFt: 8000,
        officeSqFt: 0,
        estimatedCost: "$88 million",
        startDate: null,
        expectedCompletion: "2028-12",
        description: "A proposed 15-story residential building adjacent to Union Park, offering residents direct access to green space and recreational amenities.",
        features: ["Park views", "Indoor pool", "Children's playroom", "Resident lounge", "Outdoor kitchen"],
        neighborhood: "Near West Side"
    },
    {
        id: 13,
        name: "Ashland Avenue Mixed-Use",
        address: "1700 S Ashland Ave, Chicago, IL 60608",
        lat: 41.8575,
        lng: -87.6661,
        status: "under-construction",
        type: "mixed-use",
        developer: "Riverside Investment & Development",
        architect: "Pickard Chilton",
        floors: 18,
        units: 200,
        retailSqFt: 35000,
        officeSqFt: 50000,
        estimatedCost: "$165 million",
        startDate: "2024-07",
        expectedCompletion: "2026-10",
        description: "An 18-story mixed-use development anchored by a grocery store, with residential units above and creative office space catering to tech and design firms.",
        features: ["Grocery anchor", "Public plaza", "Art installations", "Smart parking", "Electric bike share"],
        neighborhood: "Pilsen"
    },
    {
        id: 14,
        name: "Grand Avenue Tech Campus",
        address: "1000 W Grand Ave, Chicago, IL 60642",
        lat: 41.8914,
        lng: -87.6521,
        status: "completed",
        type: "commercial",
        developer: "Lincoln Property Company",
        architect: "Skidmore, Owings & Merrill",
        floors: 10,
        units: 0,
        retailSqFt: 20000,
        officeSqFt: 350000,
        estimatedCost: "$275 million",
        startDate: "2022-03",
        expectedCompletion: "2024-06",
        description: "A completed 10-story tech campus featuring open floor plates, collaborative workspaces, and amenities designed for technology companies and startups.",
        features: ["Innovation lab", "Event space", "Food hall", "Outdoor terraces", "Wellness center"],
        neighborhood: "River West"
    },
    {
        id: 15,
        name: "Van Buren Gateway",
        address: "1350 W Van Buren St, Chicago, IL 60607",
        lat: 41.8765,
        lng: -87.6610,
        status: "approved",
        type: "mixed-use",
        developer: "CMK Companies",
        architect: "VOA Associates",
        floors: 25,
        units: 290,
        retailSqFt: 22000,
        officeSqFt: 40000,
        estimatedCost: "$195 million",
        startDate: "2026-01",
        expectedCompletion: "2028-04",
        description: "A 25-story gateway development marking the western edge of the West Loop, with residential, retail, and office components designed to create a new neighborhood anchor.",
        features: ["Public art", "Community room", "Coworking space", "Rooftop farm", "Transit access"],
        neighborhood: "West Loop Gate"
    }
];

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = constructionProjects;
}
